---
title: "Energy_Spain"
author: "Stephan Kirchhoff"
date: "25 3 2020"
output: pdf_document
---



# Introduction
## An introduction/overview/executive summary section that describes the dataset and variables, and summarizes the goal of the project and key steps that were performed.

"This dataset is a daily time series of electricity demand, generation and prices in Spain from 2014 to 2018. It is gathered from ESIOS, a website managed by REE (Red Electrica Española) which is the Spanish TSO (Transmission System Operator)

A TSO main function is to operate the electrical system and to invest in new transmission (high voltage) infrastructure.
(https://www.ree.es/en/about-us/business-activities/electricity-business-in-Spain)

As a system operator, REE forecast electricity demand and offer and runs daily actions . As a result of daily actions, a PBF Plan Básico de Funcionamiento) is yielded. This is a basic schedulling of energy production (upon it several mechanisms are triggerd to ensure supply)

Enery and prices data can be downloaded from : https://www.esios.ree.es/en

OMIE (Operador del Mercado Iberico de Electricidad) is responsible for running those daily actions and also offers interesting data."

http://www.omie.es/en/inicio
                        
# Methods/Analysis
## A methods/analysis section that explains the process and techniques used, including data cleaning, data exploration and visualization, any insights gained, and your modeling approach. At least two different models or algorithms must be used, with at least one being more advanced than simple linear regression for prediction problems.

# Results
## A results section that presents the modeling results and discusses the model performance.
                        
# Conclusion 
## A conclusion section that gives a brief summary of the report, its potential impact, its limitations, and future work.
